### ISSUE TITLE
detect installed conda version to support alternative conda versions

### ISSUE THREAD

**Issue by HarryWeppner** [andrewrothstein/ansible-miniconda#21]
Currently, the presence of a conda installation would not re-install miniconda even if the conda version was different.

**Comment by HarryWeppner** [comment]
@andrewrothstein thanks for the work on this role - reported a few issues I encountered when attempting to configure conda 4.8.3 on macOS. Took the time to prepare associated PRs, which are now open. Would be great if you could give them a review - thanks again!

**Comment by andrewrothstein** [comment]
@HarryWeppner thanks for taking the time to make these thoughtful contributions! I've merged them all and published v6.0.1 to the galaxy.
