### ISSUE TITLE
Replace distutils.spawn.find_executable with shutil.which

### ISSUE THREAD

**Issue by chrisjsewell** [andrewrothstein/ansible-miniconda#28]
The `distutils.spawn.find_executable` function is not available on stock system
Python 3 in recent Debian-based distributions, `shutil.which` is a better
alternative.

**Comment by chrisjsewell** [comment]
This is from: https://github.com/andrewrothstein/ansible-miniconda/blob/ae4628130e65837581aed046b3c508cdc9768bcc/subrepos/udst.ansible-conda/conda.py#L73

I see it's a sub-package so guess maybe should add issue there

**Comment by andrewrothstein** [comment]
resolved this a while I go, I believe. lmk if u see otherwise.
