### ISSUE TITLE
Broken comment

### ISSUE THREAD

**Issue by clintval** [andrewrothstein/ansible-miniconda#7]
What did you mean to write here?

https://github.com/andrewrothstein/ansible-miniconda/blob/f0dfc4298ee75aebb8ba42a6366ea5250f0e8f8a/defaults/main.yml#L32-L33

**Comment by andrewrothstein** [comment]
I was going to add a comment about making a non-system-package the default python interpreter in those cases where the core of the operating system, e.g. the package manager, is in perhaps a different major version of python versus your root conda environment.
